/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author braccalenti.leonardo
 */
public class GraficaGioco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraficaGioco.class.getName());
    Buca b0, b1, b2, b3, b4;
    Buca[] elencoBuche;
    LogicaGioco logica;

    /**
     * Creates new form GraficaGioco
     */
    public GraficaGioco() {
        initComponents();
    }
    
    void setup(LogicaGioco logica){
        this.logica = logica;
        
        b0 = new Buca(logica);
        b1 = new Buca(logica);
        b2 = new Buca(logica);
        b3 = new Buca(logica);
        b4 = new Buca(logica);
        
        elencoBuche = new Buca[]{b0, b1, b2, b3, b4};
        
        this.getContentPane().add(b0);
        this.getContentPane().add(b1);
        this.getContentPane().add(b2);
        this.getContentPane().add(b3);
        this.getContentPane().add(b4);
        
        this.revalidate();
        this.repaint();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buca1 = new javax.swing.JButton();
        buca2 = new javax.swing.JButton();
        buca3 = new javax.swing.JButton();
        buca4 = new javax.swing.JButton();
        buca5 = new javax.swing.JButton();
        tempo = new javax.swing.JLabel();
        punteggio = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buca1.setText("jButton1");
        buca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buca1ActionPerformed(evt);
            }
        });
        getContentPane().add(buca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 117, -1, -1));

        buca2.setText("jButton2");
        getContentPane().add(buca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        buca3.setText("jButton3");
        getContentPane().add(buca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 117, -1, -1));

        buca4.setText("jButton4");
        buca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buca4ActionPerformed(evt);
            }
        });
        getContentPane().add(buca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 212, -1, -1));

        buca5.setText("jButton5");
        getContentPane().add(buca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 212, -1, -1));

        tempo.setText("tempo: 30");
        getContentPane().add(tempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 20, 78, 38));

        punteggio.setText("punteggio: 0");
        getContentPane().add(punteggio, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 20, -1, 38));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buca4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buca4ActionPerformed

    private void buca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buca1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GraficaGioco().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buca1;
    private javax.swing.JButton buca2;
    private javax.swing.JButton buca3;
    private javax.swing.JButton buca4;
    private javax.swing.JButton buca5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel punteggio;
    private javax.swing.JLabel tempo;
    // End of variables declaration//GEN-END:variables
}
